import './globals.css'
import './form.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MyProvider }  from '../components/MyContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MyProvider>
        {children}
        </MyProvider>
        </body>
    </html>
  )
}
